src/Entity/Franchise.php
<?php

namespace App\Entity;

use App\Repository\FranchiseRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;




#[ORM\Entity(repositoryClass: FranchiseRepository::class)]
class Franchise
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $isActive = null;

    #[ORM\OneToMany(mappedBy: 'Franchise', targetEntity: Structure::class, orphanRemoval: true)]
    private Collection $structures;

    #[ORM\OneToOne(mappedBy: 'Franchise', cascade: ['persist', 'remove'])]
    private ?User $user_info = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Permit $Permit = null;

    #[ORM\Column(type: Types::DATE_MUTABLE, nullable : true)]
    private ?\DateTimeInterface $last_connection = null;

    public function __construct()
    {
        $this->structures = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function isIsActive(): ?bool
    {
        return $this->isActive;
    }

    public function setIsActive(bool $isActive): self
    {
        $this->isActive = $isActive;

        return $this;
    }

    /**
     * @return Collection<int, Structure>
     */
    public function getStructures(): Collection
    {
        return $this->structures;
    }

    public function addStructure(Structure $structure): self
    {
        if (!$this->structures->contains($structure)) {
            $this->structures[] = $structure;
            $structure->setFranchise($this);
        }

        return $this;
    }

    public function removeStructure(Structure $structure): self
    {
        if ($this->structures->removeElement($structure)) {
            // set the owning side to null (unless already changed)
            if ($structure->getFranchise() === $this) {
                $structure->setFranchise(null);
            }
        }

        return $this;
    }

    public function getUserInfo(): ?User
    {
        return $this->user_info;
    }

    public function setUserInfo(?User $user_info): self
    {
        // unset the owning side of the relation if necessary
        if ($user_info === null && $this->user_info !== null) {
            $this->user_info->setFranchise(null);
        }

        // set the owning side of the relation if necessary
        if ($user_info !== null && $user_info->getFranchise() !== $this) {
            $user_info->setFranchise($this);
        }

        $this->user_info = $user_info;

        return $this;
    }

    public function getPermit(): ?Permit
    {
        return $this->Permit;
    }

    public function setPermit(Permit $Permit): self
    {
        $this->Permit = $Permit;

        return $this;
    }

    public function getLastConnection(): ?\DateTimeInterface
    {
        return $this->last_connection;
    }


    public function setLastConnection(\DateTimeInterface $last_connection): self
    {
        $this->last_connection = $last_connection;

        return $this;
    }
}

templates/content/franchises.html.twig
{% if franchises|length > 0 %}
    {% for franchise in franchises %}
        <div class="col-12 col-md-6 col-lg-4 d-flex justify-content-center p-2">
            <div class="box-wrapper {{ franchise.isActive == true ? '' :'box-inactive' }} p-2">
                <h3 class="text-center">{{franchise.userInfo.name}}</h3>
                <div>ID : {{franchise.userInfo.id}}</div>
                <div class="overflow-hidden text-nowrap">Email : <span class="lower">{{franchise.userInfo.email}}</span></div>
                <div>Structures : {{franchise.structures|length }}</div>
                {% if franchise.isActive == true %}
                <div class="green">Active</div>
                {% else %}
                <div class="red">Inactive</div>
                {% endif %}
                <div>
                <a href="{{path("app_edit_franchise", {'id': franchise.id })}}"><button class="btn-grad grad-green ">Editer</button></a>
                </div>
            </div>
        </div>
    {% endfor %}
{% else %}
    <div class="text-center mt-5 p-2 bold">Aucune structure</div>
{% endif %}

templates/content/structures.html.twig
{% if structures|length > 0 %}
        <h2 class="text-center mb-3">Les structures</h2>
    {% for structure in structures %}
    <div class="col-12 col-xl-6 mb-2 full-center">
        <div class="box-wrapper row {{ structure.isActive == true ? '' :'box-inactive' }} mb-2">
            <h3 class="overflow-hidden text-nowrap text-center">{{structure.userInfo.name}}</h3>
            <div >Id : {{structure.id}}</div>
            <div class="overflow-hidden text-nowrap"><span class="lower">{{structure.userInfo.email}}</span></div>
                {% if structure.isActive == true %}
                    <div class="green">Activée</div>
                    {% else %}
                    <div class="red ">Désactivée</div>
                {% endif %}
            <div >
                <a href="{{path("app_edit_structure", {"id" : structure.id})}}"><button class="btn-grad grad-green">Editer</button></a>
            </div>
        </div>
    </div>
    {% endfor %}
{% else %}
        <div class="text-center mt-5 p-2 bold">Aucune franchise trouvée</div>
{% endif %}