src/Entity/Permit.php
<?php

namespace App\Entity;

use App\Repository\PermitRepository;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: PermitRepository::class)]
class Permit
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column()]
    private ?int $id = null;

    #[ORM\Column]
    private ?bool $newsletter = null;

    #[ORM\Column]
    private ?bool $payment_online = null;

    #[ORM\Column]
    private ?bool $team_schedule = null;

    #[ORM\Column]
    private ?bool $live_chat = null;

    #[ORM\Column]
    private ?bool $virtual_training = null;

    #[ORM\Column]
    private ?bool $detailed_data = null;

    public function getId()
    {
        return $this->id;
    }

    public function isNewsletter(): ?bool
    {
        return $this->newsletter;
    }

    public function setNewsletter(bool $newsletter): self
    {
        $this->newsletter = $newsletter;

        return $this;
    }

    public function isPaymentOnline(): ?bool
    {
        return $this->payment_online;
    }

    public function setPaymentOnline(bool $payment_online): self
    {
        $this->payment_online = $payment_online;

        return $this;
    }

    public function isTeamSchedule(): ?bool
    {
        return $this->team_schedule;
    }

    public function setTeamSchedule(bool $team_schedule): self
    {
        $this->team_schedule = $team_schedule;

        return $this;
    }

    public function isLiveChat(): ?bool
    {
        return $this->live_chat;
    }

    public function setLiveChat(bool $live_chat): self
    {
        $this->live_chat = $live_chat;

        return $this;
    }

    public function isVirtualTraining(): ?bool
    {
        return $this->virtual_training;
    }

    public function setVirtualTraining(bool $virtual_training): self
    {
        $this->virtual_training = $virtual_training;

        return $this;
    }

    public function isDetailedData(): ?bool
    {
        return $this->detailed_data;
    }

    public function setDetailedData(bool $detailed_data): self
    {
        $this->detailed_data = $detailed_data;

        return $this;
    }
    public function setOptions(bool $common_data){
        $this->setDetailedData($common_data);
        $this->setLiveChat($common_data);
        $this->setTeamSchedule($common_data);
        $this->setPaymentOnline($common_data);
        $this->setNewsletter($common_data);
        $this->setVirtualTraining($common_data);

        return $this;
    }
}

templates/includes/navigation.html.twig
<nav class="d-flex justify-content-between align-items-center px-lg-3 px-1">
	<div class="d-flex align-items-center">
	    <a href="{{path("app_login")}}">
	    <img class="img-logo" src="{{ asset("img/logo.png") }}"/>
		<h1 hidden>Fitngo</h1>
	    </a>
	</div>
	{% block additionalItem %}
	{% endblock %}
	<div>
		<button class="btn-grad grad-red full-center p-2 logout"  id="logout" data-target="#logout-modal">
			<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-power my-1" viewBox="0 0 16 16">
				<path d="M7.5 1v7h1V1h-1z"/>
				<path d="M3 8.812a4.999 4.999 0 0 1 2.578-4.375l-.485-.874A6 6 0 1 0 11 3.616l-.501.865A5 5 0 1 1 3 8.812z"/>
			</svg>
			<span class="d-none d-xl-inline ps-2">Déconnexion</span>
		</button>
	</div>
</nav>

{# Modal déconnexion #}
<div class="modal fade" id="logout-modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered" role="document">
		<div class="modal-content p-3">
			<div class="modal-body text-center">
			<div>
				<h4>
				Déconnexion
				</h4>
			</div>
			<div class="pt-2 pb-3">
				<p>Etes-vous sûr de vouloir vous déconnecter ?</p>
			</div>
			<div class="d-flex justify-content-around">
				<button type="button" class="btn-grad grad-green" data-dismiss="modal" id="modal-logout-close">Annuler</button>
				<a href="{{path("app_logout")}}"><button class="btn-grad grad-red">Confirmer</button></a>
			</div>
			</div>
		</div>
	</div>
</div>

templates/includes/permit.html.twig
{% if (permit.newsletter) or (permit.paymentOnline) or (permit.teamSchedule) or (permit.liveChat) or (permit.virtualTraining) or (permit.detailedData) %}
    {% if (permit.paymentOnline) %}
        <div class="d-flex align-items-center green">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-lg me-1" viewBox="0 0 16 16">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
            </svg>
            <div class="overflow-hidden text-nowrap">Paiement en ligne</div>
        </div>
    {% endif %}
    {% if (permit.teamSchedule) %}
        <div class="d-flex align-items-center green">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-lg me-1" viewBox="0 0 16 16">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
            </svg>
            <div class="overflow-hidden text-nowrap">Gestion planning équipe</div>  
        </div>
    {% endif %}
    {% if (permit.liveChat) %}
        <div class="d-flex align-items-center green">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-lg me-1" viewBox="0 0 16 16">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
            </svg>
            <div class="overflow-hidden text-nowrap">Chat en ligne</div>            
        </div> 
    {% endif %}
    {% if (permit.virtualTraining) %}
        <div class="d-flex align-items-center green">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-lg me-1" viewBox="0 0 16 16">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
            </svg>
            <div class="overflow-hidden text-nowrap">Entrainements virtuels</div>          
        </div> 
    {% endif %}
    {% if (permit.detailedData) %}
        <div class="d-flex align-items-center green">
            <svg xmlns="http://www.w3.org/2000/svg" width="26" height="26" fill="currentColor" class="bi bi-check-lg me-1" viewBox="0 0 16 16">
                <path d="M12.736 3.97a.733.733 0 0 1 1.047 0c.286.289.29.756.01 1.05L7.88 12.01a.733.733 0 0 1-1.065.02L3.217 8.384a.757.757 0 0 1 0-1.06.733.733 0 0 1 1.047 0l3.052 3.093 5.4-6.425a.247.247 0 0 1 .02-.022Z"/>
            </svg>
            <div class="overflow-hidden text-nowrap">Données détaillées</div>       
        </div> 
    {% endif %}
{% else %}
    <div class="d-flex align-items-center red">
        <div class="bold h2">X</div>
        <div class="overflow-hidden text-nowrap">Aucune option activée</div>       
    </div> 
{% endif %}
    